services:
  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app

    ports:
      - "8000:8000"

    depends_on:
      postgres:
        condition: service_healthy



  postgres:
    image: postgres

    volumes:
      - ./data/db/:/var/lib/postgresql/data

    environment:
      - POSTGRES_DB=postgres_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 3


  redis:
    image: redis

    ports:
      - "6739:6739"